MVC/HandsOnHTMLHelpers/HandsOnHTMLHelpers/Models/customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;//library for validating model data
using System.ComponentModel;//ditto as above

namespace HandsOnHTMLHelpers.Models
{
    public class customer
    {
        [Required(ErrorMessage="Pls enter ID")]
        [Display(Name="CustomerId")]    
        public int cid { get; set; }
        [Required(ErrorMessage = "Pls enter customer name")]
        [Display(Name = "CustomerName")]   
        public string cname { get; set; }
        [StringLength(30, ErrorMessage="Address between 10 to 30 chars", MinimumLength=10)]
        public string address { get; set; }
        public string country { get; set; }
        public string JoinDate { get; set; }
    }
}

MVC/HandsOnHTMLHelpers/HandsOnHTMLHelpers/Controllers/customerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HandsOnHTMLHelpers.Models;

namespace HandsOnHTMLHelpers.Controllers
{
    public class customerController : Controller
    {
        //
        // GET: /customer/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult create() {
            return View();
        }

        public ActionResult show(customer obj) {
            return View(obj);
        }

    }
}

MVC/HandsOnHTMLHelpers/HandsOnHTMLHelpers/Views/customer/create.cshtml
@model HandsOnHTMLHelpers.Models.customer

@{
    ViewBag.Title = "create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>create</h2>

@using (Html.BeginForm("show","customer")) 
{
    <div id="cid">
    CustomerId:@Html.TextBoxFor(m=> m.cid) <!-- m is object of custoer-->
    </div>
    
    <div id="cname">
    CustomerName:@Html.TextBoxFor(m=> m.cname)
    </div>
    
    
    <div id="address">
    Address:@Html.TextAreaFor(m=> m.address) 
    </div>
    
     <div id="country">
    Country:@Html.DropDownListFor(m=> m.country, new SelectList(new string[]{"India", "US", "China", "UK"}))     
    </div>
    
    <div id="joindate">
    JoinDate:@Html.TextBoxFor(m=> m.JoinDate, new {type="Date"})<!-- passing as an anonymous object-->
    </div>

    <div id ="submit">
    <input type = "submit" value="Register" />
    </div>
    }
    
    

MVC/HandsOnHTMLHelpers/HandsOnHTMLHelpers/Views/customer/show.cshtml
@model HandsOnHTMLHelpers.Models.customer

@{
    ViewBag.Title = "show";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Show Details</h2>

<p>Cid:@Html.DisplayFor(m=> m.cid) </p>
<p>Cname:@Html.DisplayFor(m=> m.cname) </p>
<p>Address:@Html.DisplayFor(m=> m.address) </p>
<p>Country:@Html.DisplayFor(m=> m.country) </p>